---
- name: Docker registry to install containers
  hosts: all
  become: yes
  vars:
    docker_compose_version: "v2.20.2"
    vault_version: "latest"
    vault_volume: "vault_data"
    docker_compose_file: "/opt/docker-compose.yml"
    yannick_portfolio_version: "v3"
    yannick_portfolio_volume: "yannick_portfolio_volume"


  tasks:
    - name: Install dependencies
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present


    - name: Add Docker repository
      command: amazon-linux-extras enable docker

    - name: Install Docker
      yum:
        name: docker
        state: present


    # Step 2: Install Docker Compose
    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-$(uname -s)-$(uname -m)"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

        # Step 3: Create a Docker volume for persistence
    - name: Create Docker volume for Vault
      docker_volume:
        name: "{{ vault_volume }}"
        state: present

    - name: Create yannick portfolio volume
      docker_volume:
        name: "{{ yannick_portfolio_volume }}"
        state: present

        # Step 4: Create Docker Compose file
    - name: Create Docker Compose file for Vault and Jenkins
      copy:
        dest: "{{ docker_compose_file }}"
        content: |
          version: '3'
          services:
            vault:
              image: "vault:{{ vault_version }}"
              container_name: vault
              ports:
                - "8200:8200"
              environment:
                VAULT_DEV_ROOT_TOKEN_ID: "root"
                VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
              volumes:
                - "{{ vault_volume }}:/vault/data"

            yannick-portfolio:
              image: "yandjoumbi/yannick-portfolio:{{ yannick_portfolio_version }}"
              container_name: yannick-portfolio
              ports:
                - "3000:3000"
              volumes:
                - "{{ yannick_portfolio_volume }}:/var/jenkins_home"

        # Step 5: Start services using Docker Compose
    - name: Run Docker Compose to start Vault and Jenkins
      command: docker-compose -f "{{ docker_compose_file }}" up -d

        # Step 6: Verify containers are running
    - name: Verify Vault container is running
      docker_container_info:
        name: vault
      register: vault_status

    - name: Display Vault container status
      debug:
        msg: "Vault container is {{ vault_status.state.Status }}"

    - name: Verify yannick-portfolio container is running
      docker_container_info:
        name: yannick-portfolio
      register: yannick-portfolio_status

    - name: Display Jenkins container status
      debug:
        msg: "yannick-portfolio container is {{ yannick-portfolio_status.state.Status }}"