stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the project..."
    - # Add your build commands here, like `mvn package` for Java, or `npm install` for Node.js.

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - # Add your test commands here, like `mvn test` for Java, or `npm test` for Node.js.

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the project..."
    - # Add deployment commands here, e.g., AWS CLI, Terraform, or any deployment tool.
  only:
    - yannick  # This ensures the deployment only runs on the `main` branch.
