---
- name: Install harshircorp repo
  hosts: all
  become: yes

  vars:
    base_url: "https://rpm.releases.hashicorp.com/AmazonLinux/2023/x86_64/stable"
    gpgkey: "https://rpm.releases.hashicorp.com/gpg"
    terraform_version: "terraform-1.7.3"

  tasks:
    - name: Add harshicorp repo using yum repository
      yum_repository:
        name: hashicorp
        description: "HashiCorp Stable - $basearch"
        baseurl: "{{ base_url }}"
        gpgkey: "{{ gpgkey }}"
        enabled: yes
        state: present

    - name: Install a specific version of terraform
      yum:
        name: "{{ terraform_version }}"
        state: present

    - name: Verify terraform version
      command: terraform --version
      register: terraform_version_output

    - name: Display Terraform version
      debug:
        msg: "{{terraform_version_output}}"