name: Deploy Static Website to S3

on:
  push:
    branches:
      - yannick

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: sudo apt-get install -y awscli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Sync files to S3
      run: |
        aws s3 sync cloudfront/web-site s3://bucket-static-web --delete --acl public-read

#    - name: Invalidate CloudFront (optional)
#      run: |
#        aws cloudfront create-invalidation --distribution-id YOUR_DISTRIBUTION_ID --paths "/*"
#      env:
#        DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}  # Add this as a secret if using CloudFront for caching
#      if: success() && secrets.CLOUDFRONT_DISTRIBUTION_ID

