name: Terraform Pipeline

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS credentials for Terraform (optional, if you're using AWS)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 # Change this to your region

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.3 # Change this if needed

      # Navigate to the Terraform directory
      - name: Navigate to Terraform directory
        run: cd terraform

      # Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      # Terraform Apply (only on push, not on pull request)
      - name: Terraform Apply
     #   if: github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: ./terraform
