---
- name: Install and configure Datadog on EC2 instance
  hosts: all
  become: yes

  vars_files:
    - secrets.yaml

  vars:
    datadog_api_key: "YOUR_DATADOG_API_KEY"  # Replace with your actual API key
    playbook_version: "1.0.0"
    DD_SITE: "us5.datadoghq.com"
    DD_url: "https://install.datadoghq.com/scripts/install_script_agent7.sh"

  tasks:
    - name: Install necessary dependencies
      yum:
        name:
          - curl
        state: present

    - name: Install Datadog agent 7
      ansible.builtin.shell: |
         DD_API_KEY={{ DD_API_KEY }} \
         DD_SITE={{ DD_SITE }} \bash -c "$(curl -L {{ DD_url }})"
      args:
         executable: /bin/bash

    - name: ensure Datadog agent is running
      systemd:
        name: datadog-agent
        state: started
        enabled: yes

