---
- name: Install and configure Datadog on EC2 instance
  hosts: all
  become: yes

  vars:
    datadog_api_key: "YOUR_DATADOG_API_KEY"  # Replace with your actual API key

  tasks:
    - name: Install prerequisites
      yum:
        name:
          - curl
          - yum-utils
        state: present

    - name: Add Datadog Yum repository
      yum_repository:
        name: datadog
        description: "Datadog Agent Repository"
        baseurl: "https://yum.datadoghq.com/stable/7/x86_64/"
        gpgcheck: yes
        gpgkey: "https://yum.datadoghq.com/DATADOG_RPM_KEY.public"
        state: present

    - name: Install Datadog Agent
      yum:
        name: datadog-agent
        state: present

    - name: Configure Datadog Agent with your API key
      template:
        src: datadog.yaml.j2
        dest: /etc/datadog-agent/datadog.yaml
        owner: dd-agent
        group: dd-agent
        mode: 0644

    - name: Enable and start Datadog Agent
      service:
        name: datadog-agent
        enabled: yes
        state: started

    - name: Ensure Datadog Agent is running
      shell: systemctl is-active --quiet datadog-agent
      register: datadog_running
      ignore_errors: yes

    - name: Fail if Datadog Agent is not running
      fail:
        msg: "Datadog Agent is not running"
      when: datadog_running.rc != 0
